### ISSUE TITLE
xCode 8 and Swift 3 support

### ISSUE THREAD

**Issue by wm-j-ray** [Liquidsoul/XCTestPlayground#6]
I tried to convert it to Swift 3 and she failed on line 238.
I'd really like to use this if possible
And thanx in advance

![screen shot 2016-06-18 at 3 39 14 pm](https://cloud.githubusercontent.com/assets/770852/16173298/e16964c8-356a-11e6-8fda-c8be7135b452.png)

**Comment by Liquidsoul** [comment]
Hi @wm-j-ray!
Thank you a lot for your feedback. I have looked into it and just pushed a branch [`swift3`](https://github.com/Liquidsoul/XCTestPlayground/tree/swift3) supporting Xcode 8 with swift 3.
Because Xcode 8 and swift 3 are still in beta / preview, I won't merge this in `master` this now. I'll wait until the official release 😉 

I'll close this issue as it should solve your problem but feel free to open others if you run into another problem! 😄

**Comment by wm-j-ray** [comment]
Thank you so much.
